---
- hosts: all
    
  vars_files:
    - ../satellite-capsule-roles/roles/capsule_install/vars/vars.yml
    - ../satellite-capsule-roles/roles/satellite_install/vars/vars.yml

  tasks:
    # - import_role:
    #     name: satellite_install

    - import_role:
        name: capsule_install
    
